name: viscnn

channels:
  - pytorch
  - plotly
  - conda-forge
  - anaconda

dependencies:
  - python=3.7.*
  - pytorch=1.6.0 
  - torchvision=0.7.0
  - pandas=1.0.5
  - Pillow=8.1.2
  - jupyterlab=3.0.16
  - ipykernel=5.3.4
  - scikit-learn=0.23.*
  - sympy=1.6.2
  - plotly=4.14.3
  - dash=1.20.0
  - dash-daq=0.5.*
  - flask-caching=1.10.1
  - umap-learn=0.5.1
  - hdbscan=0.8.27
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - python-kaleido=0.2.1
  - pip=21.1.2

  - pip:
      - torch-lucent==0.1.8

